import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function hashPassword(password: string): Promise<string> {
  return bcrypt.hash(password, 12);
}

async function main() {
  console.log('Seeding database...');

  // ─── Users ─────────────────────────────────────

  const adminPassword = await hashPassword('admin123');
  const customerPassword = await hashPassword('password123');

  const admin = await prisma.user.upsert({
    where: { email: 'admin@pawparadise.com' },
    update: {},
    create: {
      name: 'Admin User',
      email: 'admin@pawparadise.com',
      passwordHash: adminPassword,
      role: 'ADMIN',
      avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
    },
  });

  const jane = await prisma.user.upsert({
    where: { email: 'jane@example.com' },
    update: {},
    create: {
      name: 'Jane Smith',
      email: 'jane@example.com',
      passwordHash: customerPassword,
      role: 'CUSTOMER',
      avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face',
    },
  });

  const john = await prisma.user.upsert({
    where: { email: 'john@example.com' },
    update: {},
    create: {
      name: 'John Doe',
      email: 'john@example.com',
      passwordHash: customerPassword,
      role: 'CUSTOMER',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face',
    },
  });

  console.log(`  Created ${3} users`);

  // ─── Products ──────────────────────────────────

  const productsData = [
    // ────────────────────────── FOOD ──────────────────────────
    {
      name: 'Premium Chicken & Rice Dog Food',
      slug: 'premium-chicken-rice-dog-food',
      category: 'FOOD' as const,
      petType: 'DOG' as const,
      brand: 'NutriPaws',
      price: 54.99,
      originalPrice: 64.99,
      image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&h=600&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1568640347023-a616a30bc3bd?w=800&h=600&fit=crop',
      ],
      description: 'Premium dry dog food made with real chicken as the first ingredient. Formulated with essential vitamins, minerals, and omega fatty acids for a healthy coat and strong immune system. Suitable for adult dogs of all breeds.',
      features: ['Real chicken #1 ingredient', 'No artificial preservatives', 'Omega 3 & 6 fatty acids', 'Supports healthy digestion', 'Made in USA'],
      weight: '30 lbs',
      rating: 4.8,
      reviewCount: 342,
      featured: true,
      inStock: true,
      stockCount: 150,
      sku: 'NP-DF-001',
    },
    {
      name: 'Grain-Free Salmon Cat Food',
      slug: 'grain-free-salmon-cat-food',
      category: 'FOOD' as const,
      petType: 'CAT' as const,
      brand: 'WhiskerBites',
      price: 42.99,
      image: 'https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1615497001839-b0a0eac3274c?w=800&h=600&fit=crop'],
      description: 'Grain-free formula crafted with wild-caught salmon for cats with sensitive stomachs. Rich in protein and taurine for heart health and sharp vision. Perfect for indoor cats.',
      features: ['Wild-caught salmon', 'Grain-free formula', 'High protein content', 'Added taurine', 'Indoor cat formula'],
      weight: '14 lbs',
      rating: 4.7,
      reviewCount: 218,
      featured: true,
      inStock: true,
      stockCount: 95,
      sku: 'WB-CF-001',
    },
    {
      name: 'Tropical Flake Fish Food',
      slug: 'tropical-flake-fish-food',
      category: 'FOOD' as const,
      petType: 'FISH' as const,
      brand: 'AquaLife',
      price: 8.99,
      image: 'https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=800&h=600&fit=crop'],
      description: 'Color-enhancing tropical fish flakes with a balanced blend of proteins, vitamins, and minerals. Keeps water cleaner with less waste. Ideal for all tropical freshwater fish.',
      features: ['Color-enhancing formula', 'Less waste, cleaner water', 'Balanced nutrition', 'For all tropical fish'],
      weight: '7.06 oz',
      rating: 4.5,
      reviewCount: 156,
      featured: false,
      inStock: true,
      stockCount: 200,
      sku: 'AL-FF-001',
    },
    {
      name: 'Organic Seed Mix for Parrots',
      slug: 'organic-seed-mix-parrots',
      category: 'FOOD' as const,
      petType: 'BIRD' as const,
      brand: 'FeatherFeast',
      price: 24.99,
      image: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=800&h=600&fit=crop'],
      description: 'Premium organic seed blend specially formulated for parrots and large birds. Includes sunflower seeds, safflower, pumpkin seeds, and dried fruits for a nutritious and delicious diet.',
      features: ['100% organic seeds', 'No fillers or additives', 'Includes dried fruits', 'Rich in vitamins', 'For parrots & large birds'],
      weight: '5 lbs',
      rating: 4.6,
      reviewCount: 89,
      featured: false,
      inStock: true,
      stockCount: 75,
      sku: 'FF-BF-001',
    },
    {
      name: 'Lamb & Sweet Potato Puppy Food',
      slug: 'lamb-sweet-potato-puppy-food',
      category: 'FOOD' as const,
      petType: 'DOG' as const,
      brand: 'NutriPaws',
      price: 48.99,
      originalPrice: 58.99,
      image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&h=600&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?w=800&h=600&fit=crop',
      ],
      description: 'Specially formulated puppy food with New Zealand lamb and sweet potato. Enriched with DHA for brain development and calcium for growing bones. Small kibble size perfect for small mouths. No corn, wheat, or soy.',
      features: ['New Zealand lamb protein', 'DHA for brain development', 'Calcium for strong bones', 'Small kibble for puppies', 'No corn, wheat, or soy'],
      weight: '25 lbs',
      rating: 4.9,
      reviewCount: 267,
      featured: true,
      inStock: true,
      stockCount: 110,
      sku: 'NP-PF-001',
    },
    {
      name: 'Indoor Hairball Control Cat Food',
      slug: 'indoor-hairball-control-cat-food',
      category: 'FOOD' as const,
      petType: 'CAT' as const,
      brand: 'WhiskerBites',
      price: 38.99,
      image: 'https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?w=800&h=600&fit=crop'],
      description: 'Specially crafted for indoor cats prone to hairballs. High-fiber blend promotes healthy digestion and reduces hairball formation. Real turkey as the first ingredient with added prebiotics for gut health.',
      features: ['Hairball control formula', 'Real turkey first ingredient', 'Added prebiotics', 'Weight management support', 'For indoor cats'],
      weight: '12 lbs',
      rating: 4.6,
      reviewCount: 183,
      featured: false,
      inStock: true,
      stockCount: 88,
      sku: 'WB-CF-002',
    },
    // ────────────────────────── TOYS ──────────────────────────
    {
      name: 'Indestructible Chew Bone',
      slug: 'indestructible-chew-bone',
      category: 'TOYS' as const,
      petType: 'DOG' as const,
      brand: 'ToughPup',
      price: 18.99,
      image: 'https://images.unsplash.com/photo-1535008652995-e95986556e32?w=600&h=600&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1535008652995-e95986556e32?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&h=600&fit=crop',
      ],
      description: 'Ultra-durable nylon chew bone designed for aggressive chewers. Infused with real bacon flavor to keep dogs engaged for hours. Cleans teeth and freshens breath while chewing.',
      features: ['Virtually indestructible', 'Bacon flavored', 'Cleans teeth while chewing', 'Non-toxic materials', 'For dogs 35+ lbs'],
      weight: '12 oz',
      dimensions: '8 x 3 x 2 in',
      rating: 4.6,
      reviewCount: 521,
      featured: true,
      inStock: true,
      stockCount: 300,
      sku: 'TP-DT-001',
    },
    {
      name: 'Interactive Feather Wand Cat Toy',
      slug: 'interactive-feather-wand-cat-toy',
      category: 'TOYS' as const,
      petType: 'CAT' as const,
      brand: 'PurrPlay',
      price: 12.99,
      originalPrice: 16.99,
      image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1574158622682-e40e69881006?w=800&h=600&fit=crop'],
      description: 'Telescopic feather wand with interchangeable attachments. Stimulates your cat\'s natural hunting instincts and provides essential exercise. Comes with 3 feather refills and a bell attachment.',
      features: ['Telescopic wand (extends to 38")', '3 feather refills included', 'Bell attachment', 'Stimulates hunting instincts', 'Lightweight & easy to use'],
      weight: '4 oz',
      dimensions: '15-38 in (extended)',
      rating: 4.9,
      reviewCount: 789,
      featured: true,
      inStock: true,
      stockCount: 450,
      sku: 'PP-CT-001',
    },
    {
      name: 'Rope Tug & Fetch Toy',
      slug: 'rope-tug-fetch-toy',
      category: 'TOYS' as const,
      petType: 'DOG' as const,
      brand: 'ToughPup',
      price: 14.49,
      image: 'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1560807707-8cc77767d783?w=800&h=600&fit=crop'],
      description: 'Multi-colored cotton rope toy perfect for tug-of-war and fetch. Helps clean teeth and massage gums during play. Machine washable and built to withstand tough play sessions.',
      features: ['100% natural cotton', 'Cleans teeth during play', 'Machine washable', 'Multiple grip points', 'Great for tug & fetch'],
      weight: '10 oz',
      dimensions: '18 x 3 in',
      rating: 4.4,
      reviewCount: 302,
      featured: false,
      inStock: true,
      stockCount: 180,
      sku: 'TP-DT-002',
    },
    {
      name: 'Squeaky Plush Duck Dog Toy',
      slug: 'squeaky-plush-duck-dog-toy',
      category: 'TOYS' as const,
      petType: 'DOG' as const,
      brand: 'ToughPup',
      price: 11.99,
      image: 'https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1591946614720-90a587da4a36?w=800&h=600&fit=crop'],
      description: 'Adorable plush duck with a built-in squeaker that dogs go crazy for. Double-stitched seams for extra durability. Soft enough to cuddle but tough enough for moderate chewers. Crinkle wings add extra excitement.',
      features: ['Built-in squeaker', 'Double-stitched seams', 'Crinkle wing inserts', 'Soft plush exterior', 'Perfect for fetch & cuddle'],
      weight: '5 oz',
      dimensions: '10 x 6 x 4 in',
      rating: 4.5,
      reviewCount: 415,
      featured: false,
      inStock: true,
      stockCount: 220,
      sku: 'TP-DT-003',
    },
    {
      name: 'Laser Pointer Cat Toy',
      slug: 'laser-pointer-cat-toy',
      category: 'TOYS' as const,
      petType: 'CAT' as const,
      brand: 'PurrPlay',
      price: 9.99,
      image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&h=600&fit=crop'],
      description: 'USB-rechargeable laser pointer with 5 different beam patterns. Provides endless interactive fun for cats and helps them get their daily exercise. Built-in LED flashlight feature. Eye-safe Class IIIA laser.',
      features: ['USB rechargeable', '5 beam patterns', 'Built-in LED flashlight', 'Eye-safe Class IIIA laser', 'Compact keychain design'],
      weight: '1 oz',
      dimensions: '4.5 x 0.6 in',
      rating: 4.3,
      reviewCount: 632,
      featured: false,
      inStock: true,
      stockCount: 350,
      sku: 'PP-CT-002',
    },
    // ────────────────────────── BEDS ──────────────────────────
    {
      name: 'Orthopedic Memory Foam Dog Bed',
      slug: 'orthopedic-memory-foam-dog-bed',
      category: 'BEDS' as const,
      petType: 'DOG' as const,
      brand: 'SnugglePaws',
      price: 79.99,
      originalPrice: 99.99,
      image: 'https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1601758174114-e711c0cbaa69?w=800&h=600&fit=crop'],
      description: 'Premium orthopedic dog bed with 4-inch memory foam base for superior joint support. Removable, machine-washable cover in neutral gray. Waterproof liner protects the foam. Ideal for senior dogs or breeds prone to hip issues.',
      features: ['4" memory foam base', 'Removable washable cover', 'Waterproof liner', 'Non-slip bottom', 'Ideal for senior dogs'],
      weight: '8 lbs',
      dimensions: '36 x 28 x 6 in',
      rating: 4.8,
      reviewCount: 463,
      featured: true,
      inStock: true,
      stockCount: 60,
      sku: 'SP-DB-001',
    },
    {
      name: 'Cozy Cave Cat Bed',
      slug: 'cozy-cave-cat-bed',
      category: 'BEDS' as const,
      petType: 'CAT' as const,
      brand: 'SnugglePaws',
      price: 34.99,
      image: 'https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1573865526739-10659fec78a5?w=800&h=600&fit=crop'],
      description: 'Enclosed cave-style cat bed with ultra-soft sherpa lining. The hooded design provides a sense of security cats love. Collapsible for easy travel and storage.',
      features: ['Sherpa fleece lining', 'Hooded cave design', 'Collapsible & portable', 'Machine washable', 'Anti-slip base'],
      weight: '2 lbs',
      dimensions: '18 x 16 x 14 in',
      rating: 4.7,
      reviewCount: 287,
      featured: false,
      inStock: true,
      stockCount: 85,
      sku: 'SP-CB-001',
    },
    {
      name: 'Elevated Cooling Dog Bed',
      slug: 'elevated-cooling-dog-bed',
      category: 'BEDS' as const,
      petType: 'DOG' as const,
      brand: 'SnugglePaws',
      price: 49.99,
      originalPrice: 59.99,
      image: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1534361960057-19889db9621e?w=800&h=600&fit=crop'],
      description: 'Raised mesh dog bed that promotes airflow for maximum cooling on hot days. Powder-coated steel frame supports up to 150 lbs. Breathable Teslin mesh fabric is easy to clean and resists mold and mildew. Perfect for outdoor or indoor use.',
      features: ['Elevated airflow design', 'Supports up to 150 lbs', 'Breathable Teslin mesh', 'Rust-proof steel frame', 'Indoor & outdoor use'],
      weight: '6 lbs',
      dimensions: '42 x 30 x 8 in',
      rating: 4.6,
      reviewCount: 324,
      featured: false,
      inStock: true,
      stockCount: 45,
      sku: 'SP-DB-002',
    },
    // ────────────────────────── ACCESSORIES ──────────────────────────
    {
      name: 'Adjustable No-Pull Dog Harness',
      slug: 'adjustable-no-pull-dog-harness',
      category: 'ACCESSORIES' as const,
      petType: 'DOG' as const,
      brand: 'WalkRight',
      price: 29.99,
      image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=600&fit=crop'],
      description: 'Ergonomic no-pull harness with front and back leash attachments. Breathable mesh padding for all-day comfort. Reflective stitching for nighttime visibility. Available in multiple sizes.',
      features: ['Front & back D-rings', 'Breathable mesh padding', 'Reflective stitching', '4 adjustment points', 'Sizes S to XL'],
      weight: '8 oz',
      rating: 4.7,
      reviewCount: 1204,
      featured: true,
      inStock: true,
      stockCount: 200,
      sku: 'WR-DH-001',
    },
    {
      name: 'Automatic Cat Water Fountain',
      slug: 'automatic-cat-water-fountain',
      category: 'ACCESSORIES' as const,
      petType: 'CAT' as const,
      brand: 'PurrFlow',
      price: 39.99,
      originalPrice: 49.99,
      image: 'https://images.unsplash.com/photo-1555685812-4b943f1cb0eb?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1555685812-4b943f1cb0eb?w=800&h=600&fit=crop'],
      description: 'Ultra-quiet automatic water fountain that encourages cats to drink more. Triple filtration system keeps water fresh and clean. 2.5L capacity lasts for days. BPA-free and dishwasher safe.',
      features: ['Ultra-quiet pump (<30dB)', 'Triple filtration system', '2.5L capacity', 'BPA-free materials', 'Dishwasher safe parts'],
      weight: '1.5 lbs',
      dimensions: '7.5 x 7.5 x 5.5 in',
      rating: 4.6,
      reviewCount: 567,
      featured: false,
      inStock: true,
      stockCount: 120,
      sku: 'PF-CW-001',
    },
    {
      name: 'Retractable Dog Leash – 16ft',
      slug: 'retractable-dog-leash-16ft',
      category: 'ACCESSORIES' as const,
      petType: 'DOG' as const,
      brand: 'WalkRight',
      price: 22.49,
      image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&h=600&fit=crop'],
      description: 'Smooth retractable leash extending up to 16 feet for dogs up to 110 lbs. One-button lock and release. Ergonomic rubberized handle with wrist strap. Tangle-free nylon cord.',
      features: ['Extends to 16 feet', 'One-button lock system', 'Ergonomic handle', 'For dogs up to 110 lbs', 'Tangle-free cord'],
      weight: '10 oz',
      rating: 4.3,
      reviewCount: 892,
      featured: false,
      inStock: true,
      stockCount: 175,
      sku: 'WR-DL-001',
    },
    {
      name: 'Personalized Leather Dog Collar',
      slug: 'personalized-leather-dog-collar',
      category: 'ACCESSORIES' as const,
      petType: 'DOG' as const,
      brand: 'WalkRight',
      price: 34.99,
      originalPrice: 44.99,
      image: 'https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=600&h=600&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=800&h=600&fit=crop',
      ],
      description: 'Handcrafted genuine leather collar with a brass nameplate that can be engraved with your pet\'s name and your phone number. Soft padded interior prevents chafing. Classic look that ages beautifully over time.',
      features: ['Genuine leather construction', 'Brass nameplate included', 'Soft padded interior', 'Rust-proof hardware', 'Sizes XS to XL'],
      weight: '4 oz',
      rating: 4.8,
      reviewCount: 956,
      featured: true,
      inStock: true,
      stockCount: 130,
      sku: 'WR-DC-001',
    },
    {
      name: 'Stainless Steel Double Pet Bowl',
      slug: 'stainless-steel-double-pet-bowl',
      category: 'ACCESSORIES' as const,
      petType: 'ALL' as const,
      brand: 'PurrFlow',
      price: 19.99,
      image: 'https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1541781774459-bb2af2f05b55?w=800&h=600&fit=crop'],
      description: 'Premium stainless steel double bowl set with a bamboo stand. One side for food and one for water. Tilted 15-degree angle reduces neck strain. Removable bowls are dishwasher safe. Non-slip silicone feet keep it in place.',
      features: ['Food-grade stainless steel', 'Bamboo raised stand', '15-degree tilt angle', 'Dishwasher safe bowls', 'Non-slip silicone feet'],
      weight: '2 lbs',
      dimensions: '14 x 7 x 4 in',
      rating: 4.7,
      reviewCount: 438,
      featured: false,
      inStock: true,
      stockCount: 160,
      sku: 'PF-PB-001',
    },
    // ────────────────────────── GROOMING ──────────────────────────
    {
      name: 'Professional Deshedding Brush',
      slug: 'professional-deshedding-brush',
      category: 'GROOMING' as const,
      petType: 'DOG' as const,
      brand: 'FurFree',
      price: 27.99,
      image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=600&fit=crop'],
      description: 'Veterinarian-recommended deshedding tool that reduces shedding by up to 90%. Stainless steel edge reaches through the topcoat to safely remove loose undercoat hair. Ergonomic handle with FurEjector button.',
      features: ['Reduces shedding up to 90%', 'Stainless steel edge', 'FurEjector button', 'Ergonomic handle', 'For medium to large dogs'],
      weight: '6 oz',
      dimensions: '7 x 4 x 2 in',
      rating: 4.8,
      reviewCount: 1543,
      featured: true,
      inStock: true,
      stockCount: 250,
      sku: 'FRF-DB-001',
    },
    {
      name: 'Oatmeal & Aloe Pet Shampoo',
      slug: 'oatmeal-aloe-pet-shampoo',
      category: 'GROOMING' as const,
      petType: 'ALL' as const,
      brand: 'GentleCoat',
      price: 15.99,
      image: 'https://images.unsplash.com/photo-1585095595205-e68428a9e205?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1585095595205-e68428a9e205?w=800&h=600&fit=crop'],
      description: 'Gentle, soap-free shampoo formulated with colloidal oatmeal and aloe vera. Soothes dry, itchy skin while leaving a fresh, clean scent. pH-balanced for pets. Safe for dogs and cats of all ages.',
      features: ['Colloidal oatmeal & aloe', 'Soap-free formula', 'pH-balanced for pets', 'Soothes itchy skin', 'Safe for dogs & cats'],
      weight: '16 oz',
      rating: 4.7,
      reviewCount: 678,
      featured: false,
      inStock: true,
      stockCount: 310,
      sku: 'GC-PS-001',
    },
    {
      name: 'Cordless Pet Grooming Clippers',
      slug: 'cordless-pet-grooming-clippers',
      category: 'GROOMING' as const,
      petType: 'ALL' as const,
      brand: 'FurFree',
      price: 39.99,
      originalPrice: 49.99,
      image: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=800&h=600&fit=crop'],
      description: 'Professional-grade cordless pet clippers with a low-vibration, ultra-quiet motor that won\'t scare nervous pets. Ceramic blade stays sharp and cool. 4 guide combs included (3mm, 6mm, 9mm, 12mm). USB rechargeable with 3-hour battery life.',
      features: ['Ultra-quiet motor (<50dB)', 'Ceramic blade stays cool', '4 guide combs included', 'USB rechargeable', '3-hour battery life'],
      weight: '9 oz',
      dimensions: '7 x 2 x 1.5 in',
      rating: 4.5,
      reviewCount: 372,
      featured: false,
      inStock: true,
      stockCount: 95,
      sku: 'FRF-GC-001',
    },
    {
      name: 'Nail Grinder for Dogs & Cats',
      slug: 'nail-grinder-dogs-cats',
      category: 'GROOMING' as const,
      petType: 'ALL' as const,
      brand: 'GentleCoat',
      price: 21.99,
      image: 'https://images.unsplash.com/photo-1450778869180-e20cdfbd5c5a?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1450778869180-e20cdfbd5c5a?w=800&h=600&fit=crop'],
      description: 'Painless electric nail grinder with 2-speed settings and 3 grinding ports for different nail sizes. Whisper-quiet operation reduces pet anxiety. Diamond bit grinder smooths nails safely without the risk of cutting too short.',
      features: ['2-speed settings', '3 grinding port sizes', 'Whisper-quiet motor', 'Diamond bit grinder', 'USB rechargeable'],
      weight: '4 oz',
      dimensions: '6 x 1 x 1 in',
      rating: 4.4,
      reviewCount: 521,
      featured: false,
      inStock: true,
      stockCount: 185,
      sku: 'GC-NG-001',
    },
    // ────────────────────────── HEALTH ──────────────────────────
    {
      name: 'Joint Support Soft Chews for Dogs',
      slug: 'joint-support-soft-chews-dogs',
      category: 'HEALTH' as const,
      petType: 'DOG' as const,
      brand: 'VetPro',
      price: 32.99,
      image: 'https://images.unsplash.com/photo-1579396349520-1c8e0a1dfd42?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1579396349520-1c8e0a1dfd42?w=800&h=600&fit=crop'],
      description: 'Veterinarian-formulated joint supplement with glucosamine, chondroitin, and MSM. Helps maintain healthy cartilage and joint function. Soft, chicken-flavored chews dogs love. 90-day supply.',
      features: ['Glucosamine & chondroitin', 'MSM for inflammation', 'Chicken flavored', '90-day supply', 'Vet recommended'],
      weight: '12 oz',
      rating: 4.9,
      reviewCount: 412,
      featured: true,
      inStock: true,
      stockCount: 140,
      sku: 'VP-JS-001',
    },
    {
      name: 'Calming Treats for Cats',
      slug: 'calming-treats-cats',
      category: 'HEALTH' as const,
      petType: 'CAT' as const,
      brand: 'VetPro',
      price: 19.99,
      image: 'https://images.unsplash.com/photo-1504450874802-0ba2bcd659e0?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1504450874802-0ba2bcd659e0?w=800&h=600&fit=crop'],
      description: 'Natural calming treats with L-theanine, chamomile, and valerian root. Helps reduce anxiety during thunderstorms, vet visits, and travel. No drowsiness formula. 60-count jar.',
      features: ['L-theanine & chamomile', 'Valerian root extract', 'No drowsiness', '60 treats per jar', 'Natural ingredients'],
      weight: '6 oz',
      rating: 4.5,
      reviewCount: 234,
      featured: false,
      inStock: true,
      stockCount: 180,
      sku: 'VP-CC-001',
    },
    {
      name: 'Flea & Tick Prevention Drops',
      slug: 'flea-tick-prevention-drops',
      category: 'HEALTH' as const,
      petType: 'DOG' as const,
      brand: 'ShieldPet',
      price: 44.99,
      originalPrice: 54.99,
      image: 'https://images.unsplash.com/photo-1612774412771-005ed8e861d2?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1612774412771-005ed8e861d2?w=800&h=600&fit=crop'],
      description: 'Fast-acting topical flea and tick treatment that kills on contact. Waterproof formula provides 30 days of protection. Easy-to-apply squeeze tubes. 3-month supply included.',
      features: ['Kills fleas & ticks on contact', 'Waterproof formula', '30-day protection per dose', '3-month supply', 'For dogs 21-55 lbs'],
      weight: '3 oz',
      rating: 4.6,
      reviewCount: 987,
      featured: false,
      inStock: true,
      stockCount: 220,
      sku: 'SP-FT-001',
    },
    {
      name: 'Probiotic Digestive Supplement for Dogs',
      slug: 'probiotic-digestive-supplement-dogs',
      category: 'HEALTH' as const,
      petType: 'DOG' as const,
      brand: 'VetPro',
      price: 28.99,
      originalPrice: 34.99,
      image: 'https://images.unsplash.com/photo-1587559070757-f72a388edbba?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1587559070757-f72a388edbba?w=800&h=600&fit=crop'],
      description: 'Veterinary-strength probiotic powder with 10 billion CFU of beneficial bacteria per scoop. Supports healthy digestion, reduces gas and bloating, and boosts immune function. Flavorless formula mixes easily into any food. 60-day supply.',
      features: ['10 billion CFU per scoop', '6 probiotic strains', 'Flavorless powder', 'Boosts immune function', '60-day supply'],
      weight: '5 oz',
      rating: 4.7,
      reviewCount: 298,
      featured: false,
      inStock: true,
      stockCount: 155,
      sku: 'VP-PD-001',
    },
    {
      name: 'Omega-3 Fish Oil for Pets',
      slug: 'omega-3-fish-oil-pets',
      category: 'HEALTH' as const,
      petType: 'ALL' as const,
      brand: 'VetPro',
      price: 24.99,
      image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&h=600&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1587559070757-f72a388edbba?w=800&h=600&fit=crop',
      ],
      description: 'Wild Alaskan salmon oil rich in EPA and DHA omega-3 fatty acids. Promotes a shiny coat, healthy skin, strong joints, and heart health. Easy pump dispenser attaches to any bottle. For dogs and cats of all sizes.',
      features: ['Wild Alaskan salmon oil', 'EPA & DHA omega-3s', 'Promotes shiny coat', 'Supports joint health', 'Easy pump dispenser'],
      weight: '16 oz',
      rating: 4.8,
      reviewCount: 723,
      featured: true,
      inStock: true,
      stockCount: 200,
      sku: 'VP-FO-001',
    },
    {
      name: 'Pet First Aid Kit',
      slug: 'pet-first-aid-kit',
      category: 'HEALTH' as const,
      petType: 'ALL' as const,
      brand: 'ShieldPet',
      price: 29.99,
      image: 'https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=600&h=600&fit=crop',
      images: ['https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=800&h=600&fit=crop'],
      description: 'Comprehensive 45-piece first aid kit designed specifically for pets. Includes bandages, antiseptic wipes, tweezers, emergency blanket, digital thermometer, and an illustrated first aid guide. Compact case fits in any car or hiking pack.',
      features: ['45 essential pieces', 'Pet-safe antiseptic wipes', 'Digital thermometer', 'Illustrated first aid guide', 'Compact travel case'],
      weight: '1.2 lbs',
      dimensions: '8 x 5 x 3 in',
      rating: 4.9,
      reviewCount: 189,
      featured: false,
      inStock: true,
      stockCount: 75,
      sku: 'SP-FK-001',
    },
  ];

  // Create products
  const products: Record<string, string> = {};
  for (const data of productsData) {
    const product = await prisma.product.upsert({
      where: { sku: data.sku },
      update: {},
      create: data,
    });
    products[data.sku] = product.id;
  }
  console.log(`  Created ${productsData.length} products`);

  // ─── Reviews ───────────────────────────────────

  const reviewsData = [
    { productSku: 'NP-DF-001', userId: jane.id, userName: 'Jane Smith', rating: 5, comment: 'My Golden Retriever absolutely loves this food! His coat is shinier than ever and he cleans his bowl every single time. Great quality ingredients and well worth the price.' },
    { productSku: 'NP-DF-001', userId: john.id, userName: 'John Doe', rating: 4, comment: 'Good quality dog food. My picky eater actually likes it. Only wish the bag had a resealable zipper. Would definitely repurchase.' },
    { productSku: 'SP-DB-001', userId: john.id, userName: 'John Doe', rating: 5, comment: 'Our senior Lab has been sleeping so much better on this bed. The memory foam is thick and supportive. The washable cover is a huge plus since he drools a lot.' },
    { productSku: 'PP-CT-001', userId: jane.id, userName: 'Jane Smith', rating: 5, comment: 'Best cat toy we have ever purchased! Our cat goes absolutely crazy for this feather wand. She gets so much exercise now. The extra refills are a nice touch.' },
    { productSku: 'WR-DH-001', userId: jane.id, userName: 'Jane Smith', rating: 4, comment: 'Great harness! Our dog stopped pulling almost immediately. The front clip really works. Took a little while to adjust all the straps but now it fits perfectly.' },
    { productSku: 'FRF-DB-001', userId: john.id, userName: 'John Doe', rating: 5, comment: 'This brush is incredible. The amount of fur it removes is unbelievable. Our house is so much cleaner now. My Husky actually seems to enjoy being brushed with it.' },
    { productSku: 'VP-JS-001', userId: john.id, userName: 'John Doe', rating: 5, comment: 'Noticed a real improvement in our senior dog\'s mobility after just two weeks. He is back to going on longer walks. The chicken flavor means he thinks they are treats!' },
    { productSku: 'TP-DT-001', userId: jane.id, userName: 'Jane Smith', rating: 4, comment: 'Finally a toy our power chewer has not destroyed in a week! He has had this bone for over a month and it is still going strong. The bacon flavor keeps him busy for hours.' },
    { productSku: 'NP-PF-001', userId: jane.id, userName: 'Jane Smith', rating: 5, comment: 'Our new puppy is thriving on this food! The small kibble is perfect for his little mouth and he loves the lamb flavor. Already noticed his coat getting softer and shinier.' },
    { productSku: 'WR-DC-001', userId: john.id, userName: 'John Doe', rating: 5, comment: 'Gorgeous leather collar. The engraving on the brass plate is crisp and clear. The leather is thick but soft enough not to irritate. Looks even better after a few months of wear.' },
    { productSku: 'VP-FO-001', userId: jane.id, userName: 'Jane Smith', rating: 5, comment: 'My dog had dry, flaky skin and a dull coat. After two weeks of this fish oil, the transformation is incredible. His fur is silky and he stopped scratching constantly. Easy to use pump too.' },
    { productSku: 'SP-DB-002', userId: john.id, userName: 'John Doe', rating: 4, comment: 'Our dog loves sleeping on this elevated bed, especially in summer. The mesh keeps him cool and it is easy to hose off after muddy outdoor naps. Only wish it came in more colors.' },
    { productSku: 'TP-DT-003', userId: jane.id, userName: 'Jane Smith', rating: 5, comment: 'My dog carries this duck toy everywhere! It has survived months of playing and the squeaker still works perfectly. The crinkle wings are her favorite part. Bought a second one as backup.' },
    { productSku: 'FRF-GC-001', userId: john.id, userName: 'John Doe', rating: 4, comment: 'These clippers are whisper quiet. Our nervous rescue dog used to panic during grooming but he barely notices these. The ceramic blade stays cool even after 30 minutes. Great value.' },
    { productSku: 'SP-FK-001', userId: jane.id, userName: 'Jane Smith', rating: 5, comment: 'Peace of mind in a compact case. We take this on every hike with our dogs. Already used the tweezers for a thorn removal and the antiseptic wipes came in handy. The first aid guide is very clear.' },
  ];

  for (const data of reviewsData) {
    const productId = products[data.productSku];
    if (!productId) continue;

    const existing = await prisma.review.findFirst({
      where: { productId, userId: data.userId },
    });
    if (!existing) {
      await prisma.review.create({
        data: {
          productId,
          userId: data.userId,
          userName: data.userName,
          rating: data.rating,
          comment: data.comment,
        },
      });
    }
  }
  console.log(`  Created ${reviewsData.length} reviews`);

  // ─── Testimonials ──────────────────────────────

  const testimonialsData = [
    { name: 'Sarah Johnson', avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face', comment: 'PawParadise has the best selection of premium pet food I have found online. The prices are fair, shipping is fast, and my dog absolutely loves the NutriPaws chicken formula!', rating: 5, productType: 'Dog Food' },
    { name: 'Michael Chen', avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face', comment: "The orthopedic dog bed from SnugglePaws changed our senior pup's life. He sleeps through the night now and his joints seem so much better. Five stars, no question.", rating: 5, productType: 'Dog Beds' },
    { name: 'Emily Rodriguez', avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face', comment: 'I order all my cat supplies from PawParadise. The interactive toys keep my two cats entertained for hours, and the grain-free food has really helped with their digestion.', rating: 5, productType: 'Cat Supplies' },
    { name: 'David Kim', avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop&crop=face', comment: 'Great customer service and the grooming tools are professional quality. The deshedding brush is a game changer. Our house has never been this fur-free!', rating: 4, productType: 'Grooming' },
  ];

  const existingTestimonials = await prisma.testimonial.count();
  if (existingTestimonials === 0) {
    await prisma.testimonial.createMany({ data: testimonialsData });
  }
  console.log(`  Created ${testimonialsData.length} testimonials`);

  // ─── Promo Codes ───────────────────────────────

  const promoData = [
    { code: 'PAWLOVE10', discountPercent: 10 },
    { code: 'SAVE20', discountPercent: 20 },
    { code: 'WELCOME15', discountPercent: 15 },
  ];

  for (const promo of promoData) {
    await prisma.promoCode.upsert({
      where: { code: promo.code },
      update: {},
      create: promo,
    });
  }
  console.log(`  Created ${promoData.length} promo codes`);

  console.log('\nSeed completed successfully!');
}

main()
  .catch((e) => {
    console.error('Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
